name: Build Native (.so)
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NDK r26d
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Build .so
        run: |
          chmod +x build.sh
          chmod +x patch.sh || true
          ./build.sh
          echo "--- HASIL BUILD ---"
          find . -name "*.so" -ls

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crystal-so
          path: |
            **/*.so
            libs/**/*.so
            jni/**/*.so